// netlify/functions/learn-access.mjs
//
// POST { email, next? }  ->  { ok: true }   (always, so nobody can use
//                                           it to find out who has
//                                           bought a course)
//
// Emails a one-tap login link for BirdBox Learn. Only an email that has
// at least one course in learn_enrolments gets anything:
//   1. a login account is made for it if it has none (already confirmed)
//   2. a login link is generated by Supabase
//   3. the link is sent from the BirdBox domain through Resend, the same
//      way the portal's staff invites are sent (Supabase's own emails
//      are not set up for this project).

import { createClient } from "@supabase/supabase-js";

const db = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false, autoRefreshToken: false },
});

const OFFICE = "info@birdboxcoaching.com";
const FROM = process.env.ALERT_FROM || "alerts@send.birdboxcoaching.com";

const ok = () => new Response(JSON.stringify({ ok: true }), {
  status: 200, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
});

export default async (req) => {
  if (req.method !== "POST") return new Response("Method not allowed", { status: 405 });

  let body = {};
  try { body = await req.json(); } catch (e) { return ok(); }
  const email = String(body.email || "").trim().toLowerCase();
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email) || email.length > 254) return ok();

  // Only ever send people back into /learn/ on this site.
  const origin = new URL(req.url).origin;
  const next = typeof body.next === "string" && /^\/learn\/[\w\-./?=&%]*$/.test(body.next) ? body.next : "/learn/";

  try {
    const { data: enr } = await db.from("learn_enrolments").select("id").eq("email", email).limit(1);
    if (!enr || !enr.length) return ok();

    const { error: cErr } = await db.auth.admin.createUser({ email, email_confirm: true });
    if (cErr && !/already|registered|exists/i.test(cErr.message || "")) {
      console.error("learn-access createUser:", cErr.message);
    }

    const { data, error } = await db.auth.admin.generateLink({
      type: "magiclink",
      email,
      options: { redirectTo: origin + next },
    });
    if (error || !data?.properties?.action_link) {
      console.error("learn-access generateLink:", error?.message);
      return ok();
    }
    await sendLink(email, data.properties.action_link, origin);
  } catch (err) {
    console.error("learn-access:", err && (err.message || err));
  }
  return ok();
};

async function sendLink(to, link, origin) {
  const key = process.env.RESEND_API_KEY;
  if (!key) { console.warn("No Resend key; login link not sent to", to); return; }

  const text =
`Hi,

Here is your login link for your BirdBox online course:

${link}

Tap it and you go straight to My courses, logged in. The link works once and expires in 1 hour. If it has run out, ask for a new one at ${origin}/learn/

Once you are in, you can set a password under "Set or change your password" so you can log in without waiting for an email next time.

Did not ask for this? You can ignore this email.

BirdBox Coaching
${origin}/learn/`;

  const html = `<div style="font-family:-apple-system,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.6;color:#16181b;max-width:520px">
<p>Hi,</p>
<p>Here is your login link for your BirdBox online course.</p>
<p style="margin:28px 0"><a href="${link.replace(/&/g, "&amp;")}" style="display:inline-block;background:#4FA8DE;color:#0C1116;text-decoration:none;font-weight:800;letter-spacing:.08em;text-transform:uppercase;font-size:14px;padding:14px 26px">Log in to my courses</a></p>
<p>The link works once and expires in 1 hour. If it has run out, ask for a new one at <a href="${origin}/learn/">${origin.replace(/^https?:\/\//, "")}/learn</a>.</p>
<p>Once you are in, you can set a password so you can log in without waiting for an email next time.</p>
<p style="color:#6c7178;font-size:14px">Did not ask for this? You can ignore this email.</p>
<p>BirdBox Coaching</p>
</div>`;

  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: "Bearer " + key, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: `BirdBox Coaching <${FROM}>`,
        to: [to],
        reply_to: OFFICE,
        subject: "Your BirdBox course login link",
        text,
        html,
      }),
    });
    if (!res.ok) console.error("Resend rejected the login link to", to, await res.text());
  } catch (err) {
    console.error("Could not send the login link to", to, err.message);
  }
}
